spring.application.name: hiro_java

spring.profiles.group:
  "local": "local-infra,test-db"
  "test": "test-infra,test-db"
  "prod":  "prod-infra,prod-db"

springdoc.swagger-ui.path: /api/swagger-ui.html

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

---
spring.config.activate.on-profile: local-infra

S3_ID: "test-id"
S3_SECRET: "test-secret"
S3_BUCKET: "test-bucket"
S3_REGION: "test-region"
hiro.jwt.secret: "test-13123123342214512353425872348957238954792387523890758972348957324895723890"


---
spring.config.activate.on-profile: local-db
spring:
  datasource:
    driver-class-name: org.h2.Driver

---
spring.config.activate.on-profile: test-infra

S3_ID: "test-id"
S3_SECRET: "test-secret"
S3_BUCKET: "test-bucket"
S3_REGION: "test-region"
hiro.jwt.secret: "test-jwt"

---
spring.config.activate.on-profile: test-db
spring:
  datasource:
    driver-class-name: org.h2.Driver

---
spring.config.activate.on-profile: prod-infra

---
spring.config.activate.on-profile: prod-db

S3_ID: ${S3_ID}
S3_SECRET: ${S3_SECRET}
S3_BUCKET: ${S3_BUCKET}
S3_REGION: ${S3_REGION}
hiro.jwt.secret: ${JWT_SECRET}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}